{% set name = "msgraph-sdk" %}
{% set version = "1.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/msgraph_sdk-{{ version }}.tar.gz
  sha256: 6dd1ba9a46f5f0ce8599fd9610133adbd9d1493941438b5d3632fce9e55ed607

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - azure-identity >=1.12.0
    - microsoft-kiota-serialization-json >=1.8.0,<2.0.0
    - microsoft-kiota-serialization-text >=1.8.0,<2.0.0
    - microsoft-kiota-serialization-form >=1.8.0,<2.0.0
    - microsoft-kiota-serialization-multipart >=1.8.0,<2.0.0
    - msgraph-core >=1.3.1

test:
  imports:
    - msgraph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python
  summary: The Microsoft Graph Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
