{% set name = "msgraph-sdk" %}
{% set version = "1.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/msgraph_sdk-{{ version }}.tar.gz
  sha256: ef49166ada7b459b5a843ceb3d253c1ab99d8987ebf3112147eb6cbcaa101793

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - azure-identity >=1.12.0
    - microsoft-kiota-abstractions >=1.3.0,<2.0.0
    - microsoft-kiota-authentication-azure >=1.0.0,<2.0.0
    - microsoft-kiota-serialization-json >=1.3.0,<2.0.0
    - microsoft-kiota-serialization-text >=1.0.0,<2.0.0
    - microsoft-kiota-serialization-form >=0.1.0
    - microsoft-kiota-serialization-multipart >=0.1.0
    - microsoft-kiota-http >=1.0.0,<2.0.0
    - msgraph-core >=1.0.0

test:
  imports:
    - msgraph
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoftgraph/msgraph-sdk-python
  summary: The Microsoft Graph Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
